- platform: mqtt
  name: "BedroomTV_Power"
  command_topic: "bedroomIR/cmnd/irSend"
  payload_on: '{"Protocol":"RC6","Bits":36,"Data":"0xC8011120C"}'
  payload_off: '{"Protocol":"RC6","Bits":36,"Data":"0xC8011120C"}'
  optimistic: true
- platform: mqtt
  name: "BedroomTV_Volume"
  command_topic: "bedroomIR/cmnd/irSend"
  payload_on: '{"Protocol":"RC6","Bits":36,"Data":"0xC80119210"}'
  payload_off: '{"Protocol":"RC6","Bits":36,"Data":"0xC8011120C"}'
  optimistic: true
- platform: mqtt
  name: "Fade7"
  command_topic: "string/cmnd/rfcode"
  payload_on: "#FFFF10"
  payload_off: "#FFFF03"
  optimistic: true