- platform: mqtt
  state_topic: "string/tele/RESULT"
  name: "office_motion"
  value_template: >-
    {% if value_json.RfReceived.Data == 'EC498E' %}
      {{'ON'}}
    {% else %}
      {{states('binary_sensor.office_motion') | upper}}
    {% endif %}
  off_delay: 15
  device_class: motion
- platform: mqtt
  state_topic: "string/tele/RESULT"
  name: "pantry_door"
  value_template: >-
    {% if value_json.RfReceived.Data == '5CFEE9' %}
      {{'ON'}}
    {% else %}
      {{states('binary_sensor.pantry_door') | upper}}
    {% endif %}
  off_delay: 15
  device_class: door