##############################################################################
# Automations for handling toggle state buttons on page 7
automation:
  # Set font and text for toggle buttons on device connection
  - alias: hasp_master_p7_ToggleInit
    trigger:
      - platform: state
        entity_id: "binary_sensor.master_connected"
        to: "on"
      - platform: homeassistant
        event: start
    action:
      # Set font and justification for the 4 buttons (b4-b7)
      - service: mqtt.publish
        data:
          topic: "hasp/master/command/json"
          payload: '["p[7].b[4].font=7","p[7].b[5].font=7","p[7].b[6].font=7","p[7].b[7].font=7","p[7].b[4].xcen=2","p[7].b[5].xcen=2","p[7].b[6].xcen=2","p[7].b[7].xcen=1"]'
      # Set text labels for the top 3 buttons (b4-b6)
      - service: mqtt.publish
        data:
          topic: "hasp/master/command/json"
          payload: '["p[7].b[4].txt=\"Table \"","p[7].b[5].txt=\"Overhead \"","p[7].b[6].txt=\"Patio \""]'

  # Toggle light1 when p[7].b[4] pressed
  - alias: hasp_master_p7_ToggleLight1
    trigger:
      - platform: mqtt
        topic: "hasp/master/state/p[7].b[4]"
        payload: "ON"
    action:
      - service: homeassistant.toggle
        entity_id: light.kitchen_table

  # Toggle light2 when p[7].b[5] pressed
  - alias: hasp_master_p7_ToggleLight2
    trigger:
      - platform: mqtt
        topic: "hasp/master/state/p[7].b[5]"
        payload: "ON"
    action:
      - service: homeassistant.toggle
        entity_id: light.kitchen_overhead

  # Toggle light3 when p[7].b[6] pressed
  - alias: hasp_master_p7_ToggleLight3
    trigger:
      - platform: mqtt
        topic: "hasp/master/state/p[7].b[6]"
        payload: "ON"
    action:
      - service: homeassistant.toggle
        entity_id: light.patio

  # Toggle all light_toggle_group when p[7].b[7] pressed
  - alias: hasp_master_p7_ToggleAll
    trigger:
      - platform: mqtt
        topic: "hasp/master/state/p[7].b[7]"
        payload: "ON"
    action:
      - service_template: >
          {% if states.light.kitchen_lights.state == "on" -%}
            homeassistant.turn_off
          {%- else -%}
            homeassistant.turn_on
          {%- endif %}
        entity_id: light.kitchen_lights

  # Toggle colors on p[7].b[4] when light1 changes
  - alias: hasp_master_p7_ToggleColor1
    trigger:
      - platform: state
        entity_id: light.kitchen_table
      - platform: state
        entity_id: "binary_sensor.master_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_master_selectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_selectedforegroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedforegroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/master/command/json"
          payload_template: >-
            [{% if states('light.kitchen_table') == "on" -%}
              "p[7].b[4].bco={{ states('input_number.hasp_master_selectedbackgroundcolor') | int }}","p[7].b[4].pco={{ states('input_number.hasp_master_selectedforegroundcolor') | int }}"
            {%- else -%}
              "p[7].b[4].bco={{ states('input_number.hasp_master_unselectedbackgroundcolor') | int }}","p[7].b[4].pco={{ states('input_number.hasp_master_unselectedforegroundcolor') | int }}"
            {%- endif %}]

  # Toggle colors on p[7].b[5] when light2 changes
  - alias: hasp_master_p7_ToggleColor2
    trigger:
      - platform: state
        entity_id: light.kitchen_overhead
      - platform: state
        entity_id: "binary_sensor.master_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_master_selectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_selectedforegroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedforegroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/master/command/json"
          payload_template: >-
            [{% if states('light.kitchen_overhead') == "on" -%}
              "p[7].b[5].bco={{ states('input_number.hasp_master_selectedbackgroundcolor') | int }}","p[7].b[5].pco={{ states('input_number.hasp_master_selectedforegroundcolor') | int }}"
            {%- else -%}
              "p[7].b[5].bco={{ states('input_number.hasp_master_unselectedbackgroundcolor') | int }}","p[7].b[5].pco={{ states('input_number.hasp_master_unselectedforegroundcolor') | int }}"
            {%- endif %}]

  # Toggle colors on p[7].b[6] when light3 changes
  - alias: hasp_master_p7_ToggleColor3
    trigger:
      - platform: state
        entity_id: light.patio
      - platform: state
        entity_id: "binary_sensor.master_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_master_selectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_selectedforegroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedforegroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/master/command/json"
          payload_template: >-
            [{% if states('light.patio') == "on" -%}
              "p[7].b[6].bco={{ states('input_number.hasp_master_selectedbackgroundcolor') | int }}","p[7].b[6].pco={{ states('input_number.hasp_master_selectedforegroundcolor') | int }}"
            {%- else -%}
              "p[7].b[6].bco={{ states('input_number.hasp_master_unselectedbackgroundcolor') | int }}","p[7].b[6].pco={{ states('input_number.hasp_master_unselectedforegroundcolor') | int }}"
            {%- endif %}]

  # Set button 4 to "All Lights Off" if any lights are on, otherwise set to "All Lights On"
  - alias: hasp_master_p7_ToggleColorAll
    trigger:
      - platform: state
        entity_id: light.kitchen_lights
      - platform: state
        entity_id: "binary_sensor.master_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_number.hasp_master_selectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_selectedforegroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedforegroundcolor
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/master/command/json"
          payload_template: >-
            [{% if states('light.kitchen_lights') == "on" -%}
              "p[7].b[7].txt=\"All Lights Off\"","p[7].b[7].bco={{ states('input_number.hasp_master_unselectedbackgroundcolor') | int }}","p[7].b[7].pco={{ states('input_number.hasp_master_unselectedforegroundcolor') | int }}"
            {%- else -%}
              "p[7].b[7].txt=\"All Lights On\"","p[7].b[7].bco={{ states('input_number.hasp_master_selectedbackgroundcolor') | int }}","p[7].b[7].pco={{ states('input_number.hasp_master_selectedforegroundcolor') | int }}"
            {%- endif %}]

##############################################################################
# Automations to overlay icons on HASP Page 7
#
# See notes on hasp_master_p2_status for details here.  To recap:
# * Icons placed w/ `xstr` only apply to the current page, so only attempt
#   this while Page 3 is active.
# * Any button interaction (press, release, new text, new color, etc)
#   overwrites the icon, so we need to catch these events and put the icon
#   back on top.
# * The events we capture take time for the Nextion to process, so insert a
#   1 msec delay command which will allow the Nextion to fully process the
#   prior event.

  # Overlay a light icon on the left side of p[7].b[4]
  - alias: hasp_master_p7_Light1Icon
    trigger:
      - platform: state
        entity_id: "binary_sensor.master_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: mqtt
        topic: "hasp/master/command/page"
        payload: "7"
      - platform: state
        entity_id: light.kitchen_table
      - platform: mqtt
        topic: "hasp/master/state/p[7].b[4]"
        payload: "OFF"
      - platform: mqtt
        topic: "hasp/master/command/p[7].b[4].txt"
      - platform: state
        entity_id: input_number.hasp_master_selectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_selectedforegroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedforegroundcolor
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ (states('input_number.hasp_master_activepage')|int) == 7 }}"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/master/command/json"
          payload_template: >-
            [{% if states('light.kitchen_table') == "on" -%}
              "delay=1","xstr 0,2,50,65,8,65280,65535,1,1,3,\"\""
            {%- else -%}
              "delay=1","xstr 0,2,50,65,8,{{ states('input_number.hasp_master_unselectedforegroundcolor')|int }},0,1,1,3,\"\""
            {%- endif %}]

  # Overlay a light icon on the left side of p[7].b[5]
  - alias: hasp_master_p7_Light2Icon
    trigger:
      - platform: state
        entity_id: "binary_sensor.master_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: mqtt
        topic: "hasp/master/command/page"
        payload: "7"
      - platform: state
        entity_id: light.kitchen_overhead
      - platform: mqtt
        topic: "hasp/master/state/p[7].b[5]"
        payload: "OFF"
      - platform: mqtt
        topic: "hasp/master/command/p[7].b[5].txt"
      - platform: state
        entity_id: input_number.hasp_master_selectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_selectedforegroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedforegroundcolor
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ (states('input_number.hasp_master_activepage')|int) == 7 }}"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/master/command/json"
          payload_template: >-
            [{% if states('light.kitchen_overhead') == "on" -%}
              "delay=1","xstr 0,69,50,65,8,65280,0,1,1,3,\"\""
            {%- else -%}
              "delay=1","xstr 0,69,50,65,8,{{ states('input_number.hasp_master_unselectedforegroundcolor')|int }},0,1,1,3,\"\""
            {%- endif %}]

  # Overlay a light icon on the left side of p[7].b[6]
  - alias: hasp_master_p7_Light3Icon
    trigger:
      - platform: state
        entity_id: "binary_sensor.master_connected"
        to: "on"
      - platform: homeassistant
        event: start
      - platform: mqtt
        topic: "hasp/master/command/page"
        payload: "7"
      - platform: state
        entity_id: light.patio
      - platform: mqtt
        topic: "hasp/master/state/p[7].b[6]"
        payload: "OFF"
      - platform: mqtt
        topic: "hasp/master/command/p[7].b[6].txt"
      - platform: state
        entity_id: input_number.hasp_master_selectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedbackgroundcolor
      - platform: state
        entity_id: input_number.hasp_master_selectedforegroundcolor
      - platform: state
        entity_id: input_number.hasp_master_unselectedforegroundcolor
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ (states('input_number.hasp_master_activepage')|int) == 7 }}"
    action:
      - service: mqtt.publish
        data:
          topic: "hasp/master/command/json"
          payload_template: >-
            [{% if states('light.patio') == "on" -%}
              "delay=1","xstr 0,136,50,65,8,65280,0,1,1,3,\"\""
            {%- else -%}
              "delay=1","xstr 0,136,50,65,8,{{ states('input_number.hasp_master_unselectedforegroundcolor')|int }},0,1,1,3,\"\""
            {%- endif %}]