octoprint:
  host: 192.168.0.60
  api_key: !secret octoprint_api_key
  name: AnyCubicI3
  bed: true
  number_of_tools: 1

camera:
  - platform: mjpeg
    name: AnycubicI3_camera
    still_image_url: http://192.168.0.60/webcam/?action=snapshot
    mjpeg_url: http://192.168.0.60/webcam/?action=stream
    
binary_sensor:
  - id: b672dbec-358d-460f-b935-60c44fe1ec8f
    platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error