custom_header:
  active_tab_color: var(--state-icon-active-color)
  background: var(--app-header-background-color)
  compact_mode: true
  elements_color: var(--app-header-text-color)
  exceptions:
    - conditions:
        user: Logan
      config:
        default_tab: LOGANS ROOM
        disable_sidebar: true
        hide_config: true
        hide_header: true
        hide_help: true
        hide_raw: true
        hide_unused: true
        menu_hide: true
        show_tabs: LOGANS ROOM
  tab_indicator_color: var(--state-icon-active-color)
title: Mi Casa

decluttering_templates:
##################################################################################
# button_text
##################################################################################
  button_text:
    default:
    card:
      type: "custom:button-card"
      entity: input_select.remote
      name: '[[name]]'
      show_icon: false
      tap_action:
        action: call-service
        service: input_select.set_options
        service_data:
          entity_id: input_select.remote
          options: "[[name]]"
      styles:
        card:
          - background-color: >
              [[[
                if (states['input_select.remote'].state == "[[name]]")
                  return "[[background_active]]";
                return "rgba(56, 60, 69, 1)";
              ]]]
          - border-radius: 20px
          - border-style: solid
          - border-width: 3px
          - border-color: '[[border]]'
##################################################################################
# label_image
##################################################################################
  label_image:
    default:
      - height: 75
    card:
      type: custom:button-card
      color_type: label-card
      show_entity_picture: true
      entity_picture: '/local/lovelace/remote/[[image]]'
      styles:
        card:
          - background-color: rgba(56,60,69,1)
          - border-radius: 20px
          - border-style: solid
          - border-width: 3px
          - border-color: >
              [[[
                if (states['sensor.shield_app'].state == "[[name]]")
                  return "[[border_active]]";
                return "[[border_on]]";
              ]]]
          - height: '[[height]]px'
          - padding: 5px
        entity_picture:
          - height: 100%
          - width: 100%
##################################################################################
# button_image
##################################################################################
  button_image:
    default:
    card:
      type: custom:button-card
      name: '[[name]]'
      entity: '[[entity]]'
      show_name: false
      show_entity_picture: true
      entity_picture: '/local/lovelace/remote/[[image]]'
      tap_action: '[[tap_action]]'
      styles:
        card:
          - background-color: rgba(56,60,69,1)
          - border-radius: 20px
          - border-style: solid
          - border-width: 3px
          - border-color: >
              [[[
                if (states['sensor.shield_app'].state == "[[name]]")
                  return "[[border_active]]";
                return "[[border_on]]";
              ]]]
          - height: 75px
          - padding: 5px
        entity_picture:
          - height: 100%
          - width: 100%
##################################################################################
# Button for remote icon and text
##################################################################################
  button_icon_and_text:
    default:
    card:
      type: "custom:button-card"
      entity: '[[entity]]'
      icon: 'mdi:[[icon]]'
      name: '[[name]]'
      tap_action: '[[tap_action]]'
      styles:
        card:
          - background-color: rgba(56,60,69,1)
          - border-radius: 20px
          - border-style: solid
          - border-width: 3px
          - border-color: >
              [[[
                if (states['sensor.shield_app'].state == "[[name]]")
                  return "[[border_active]]";
                return "[[border_on]]";
              ]]]
          - height: 75px
          - padding: 5px

#----------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------
views:
  - !include lovelace_views/remote_navigation.yaml
  # - !include lovelace/mediaplayer.yaml
#views: !include_dir_merge_list lovelace_views/