custom_header:
  active_tab_color: var(--state-icon-active-color)
  background: var(--app-header-background-color)
  compact_mode: true
  elements_color: var(--app-header-text-color)
  exceptions:
    - conditions:
        user: Logan
      config:
        default_tab: LOGANS ROOM
        disable_sidebar: true
        hide_config: true
        hide_header: true
        hide_help: true
        hide_raw: true
        hide_unused: true
        menu_hide: true
        show_tabs: LOGANS ROOM
  tab_indicator_color: var(--state-icon-active-color)
title: Mi Casa
views: !include_dir_merge_list lovelace_views/