#######################################################################################################################
## Package - Unavailable Entities Sensor - Count and list of entities with state of unavailable, unknown, or none (null)
## NOTE: Home Assistant v0.117+ is required
#######################################################################################################################

## REQUIRED this is the template sensor
## state: number of unavailable entities
## attribute - entities: comma separated list of unavailable entity ids
sensor:
  - platform: template
    sensors:
      unavailable_entities:
        friendly_name: Unavailable Entities
        unit_of_measurement: entities
        icon_template: "{{ 'mdi:check-circle' if is_state('sensor.unavailable_entities','0') else 'mdi:alert-circle' }}"
        value_template: >
            {{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group')
              |selectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|list|count }}
        attribute_templates:
          entities: >
            {{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group')
              |selectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|map(attribute='entity_id')|join(',') }}

## REQUIRED add any entities you do not want to monitor in this group.
## This group MUST exist even if is empty for sensor template to render.
group:
  ignored_entities:
    entities:
        - sensor.plug_monitor_3_status
        - media_player.chad_s_aio
        - media_player.daniela_s_echo
        - media_player.davids_echo
        - media_player.kitchen_echo
        - media_player.living_echo
        - media_player.logans_echo
        - media_player.office_echo
        - media_player.vanessa_echo

## OPTIONAL Example automation to demonstrate how you can utilize this sensor
automation:
  - id: unavailable_entities_notification
    alias: "Unavailable Entities Notification"
    description: "Create persistent notification if there are unavailable entities, dismiss if none."
    mode: restart

    trigger:
      - platform: state
        entity_id: sensor.unavailable_entities

    action:
      - choose:
          conditions:
            - condition: numeric_state
              entity_id: sensor.unavailable_entities
              below: 1

          sequence:
            - service: persistent_notification.dismiss
              data:
                notification_id: unavailable_entities

        default:
          - service: persistent_notification.create
            data:
              title: Unavailable Entities
              message: "- {{ state_attr('sensor.unavailable_entities','entities').split(',')|join('\n- ') }}"
              notification_id: unavailable_entities








# - id: '2575573265530'
#   alias: Device Disconnected
#   description: Send a notfication when a device is disconnected
#   trigger:
#   - platform: numeric_state
#     entity_id: sensor.plug_monitor_3_status
#     below: 20
#   action:
#   - data:
#       title: "Device Disconnected"
#       message: "Daniela's TV Sensor Disconnected"
#     service: notify.mobile_app_chads_iphone_xr
#   - service: notify.persistent_notification
#     data:
#       title: "Device Disconnected"
#       message: "Daniela's TV Sensor Disconnected"