- id: '1575673164520'
  alias: Christmas Lights On
  description: Turn Christmas lights on at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id:
      - switch.led_power
    service: switch.turn_on
  - delay: '00:10:00'
  - data:
      entity_id:
      - light.ridge
    service: light.turn_on
- id: '1575673610036'
  alias: Christmas Lights Off
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id:
      - light.ridge
    service: light.turn_off
  - delay: '00:10:00'
  - data:
      entity_id:
      - switch.led_power
    service: switch.turn_off

###################################################################
######                                                      #######
######                       FPP                            #######
######                                                      #######
###################################################################
 #####  Exterior lights on at sunset  #####
- alias: "Monthly Holiday Color Scene ON"
  initial_state: True
 # hide_entity: True
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: script.monthly_color_scene

#####  Exterior lights OFF  #####
- alias: "Monthly Holiday Color Scene OFF"
  initial_state: True
  # hide_entity: True
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: script.monthly_color_off

