##############################################################################
# Automations and required components to enable "sleep mode" screen timeout.
##############################################################################
# Paste the following into your Lovelace config to control this via the UI:
##############################################################################
#      - type: entities
#        title: officehasp Screen Sleep
#        entities:
#          - entity: input_number.hasp_officehasp_sleeptime
#            name: Sleep timeout
#        show_header_toggle: false
##############################################################################

##############################################################################
input_number:
  hasp_officehasp_sleeptime:
    name: officehasp Sleep Mode Timeout in seconds
    icon: mdi:clock-end
    mode: box
    min: 0
    max: 9999
    step: 1
    unit_of_measurement: seconds

automation:
  ##############################################################################
  # Enable sleep timer
  - alias: hasp_officehasp_00_EnableSleepTime
    trigger:
      - platform: state
        entity_id: input_number.hasp_officehasp_sleeptime
      - platform: state
        entity_id: "binary_sensor.officehasp_connected"
        to: "on"
      - platform: homeassistant
        event: start
    condition:
      - condition: numeric_state
        entity_id: input_number.hasp_officehasp_sleeptime
        above: 0
    action:
      - service: mqtt.publish
        data_template:
          topic: "hasp/officehasp/command/json"
          payload_template: '["sleep=0","thup=1", "thsp={{states("input_number.hasp_officehasp_sleeptime")|int}}"]'

  ##############################################################################
  # Disable sleep timer
  - alias: hasp_officehasp_00_DisableSleepTime
    trigger:
      platform: state
      entity_id: input_number.hasp_officehasp_sleeptime
    condition:
      - condition: numeric_state
        entity_id: input_number.hasp_officehasp_sleeptime
        below: 1
    action:
      - service: mqtt.publish
        data_template:
          topic: "hasp/officehasp/command/json"
          payload: '["sleep=0", "thsp=0", "thup=0"]'
