##############################################################################
# Automations and required components to return to a specified default page
# after a period of time

timer:
  hasp_living_plate_defaultpagetimer:
    name: living_plate Default Page Timer

input_number:
  hasp_living_plate_defaultpagenumber:
    name: living_plate Default Page
    icon: mdi:format-list-numbered
    min: 1
    max: 9
    step: 1
  hasp_living_plate_defaultpagetimeout:
    name: living_plate Default Page Timeout in seconds
    icon: mdi:clock-end
    mode: box
    min: 1
    max: 9999
    step: 1

group:
  living_plate_defaultpage:
    name: living_plate Default Page
    entities:
      - input_number.hasp_living_plate_defaultpagenumber
      - input_number.hasp_living_plate_defaultpagetimeout
      - timer.hasp_living_plate_defaultpagetimer

automation:
##############################################################################
# Set timer
  - alias: hasp_living_plate_00_DefaultPageTimerSet
    trigger:
      platform: state
      entity_id: input_number.hasp_living_plate_activepage
    action:
    - service: timer.cancel
      data_template:
        entity_id: timer.hasp_living_plate_defaultpagetimer
    - service: timer.start
      data_template:
        entity_id: timer.hasp_living_plate_defaultpagetimer
        duration: '00:00:{{ states("input_number.hasp_living_plate_defaultpagetimeout") | int }}'

##############################################################################
# Set page at timer expiration
  - alias: hasp_living_plate_00_DefaultPageSet
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hasp_living_plate_defaultpagetimer
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/living_plate/command/page'
        payload_template: '{{states("input_number.hasp_living_plate_defaultpagenumber")|int}}'

##############################################################################
# Add the default page group to the main view
  - alias: hasp_living_plate_00_DefaultPageTimerGroupUpdate
    trigger:
    - platform: homeassistant
      event: start
    action:
    - service: group.set
      data_template:
        object_id: "living_plate"
        add_entities:
          - group.living_plate_defaultpage