- alias: 'Homeschool Schedule Wake up'
  id: '1585166565608'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '9:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Wake Up and Clean Your Bedrooms
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #2 Take Showers'
  id: '1585166565609'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '9:15'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Take Showers
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #3 Yoga'
  id: '1585166565610'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '9:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Time for Yoga
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #4 Breakfast'
  id: '1585166565611'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '10:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Breakfast Time
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #5 Math'
  id: '1585166565612'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '10:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Math Time
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #6 Snack'
  id: '1585166565613'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '11:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: 15 minute Break for Snacks 
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #7 English'
  id: '1585166565614'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '11:45'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Time for English
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #8 Lunch'
  id: '1585166565615'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '12:45'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: 30 minute Break for lunch
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #9 Science'
  id: '1585166565616'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '13:15'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Time for Science
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #10 Snack'
  id: '1585166565617'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '14:15'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: 15 Minute Break for Snacks
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #11 Social Studies'
  id: '1585166565618'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '14:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Time for Social Studies
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #12 Spanish'
  id: '1585166565619'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '15:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Spanish Como se dice espanol
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #13 Recess'
  id: '1585166565620'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '16:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Time for Recess
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #14 Reading'
  id: '1585166565621'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '17:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Time for Reading
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media
- alias: 'Homeschool Schedule #15 Free Time'
  id: '1585166565622'
  description: Alexa Rings a Bell for Each Subject Change
  trigger:
  - at: '18:30'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
      media_content_id: amzn_sfx_doorbell_chime_01
      media_content_type: sound
    service: media_player.play_media
  - data:
      data:
        type: tts
      message: Finally free time good work everyone
      target:
      - media_player.extra_echo
      - media_player.kitchen_echo
      - media_player.bedroom_echo_show
      - media_player.chad_s_aio
      - media_player.davids_echo
      - media_player.girls_echo
      - media_player.living_echo
      - media_player.logans_echo_show
      - media_player.office_echo
    service: notify.alexa_media