esphome:
  name: temp_flash
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret ssid_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp Flash Fallback Hotspot"
    password: "EpcUdQ5BjYwE"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
