esphome:
  name: test_nodemcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret ssid_pass
  
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.0.60
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Nodemcu Fallback Hotspot"
    password: "VQWNPHvCgLDz"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:


ota:
  password: !secret ota_pass

remote_receiver:
  pin: 
    number: D7
    inverted: yes
  dump: all

remote_transmitter:
  pin: D5
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%
 
switch:
  - platform: template
    name: "Vizio TV Power"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x20DF
          command: 0x10EF
  - platform: template
    name: "Projector Power"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x100B
          command: 0xCBD
  - platform: template
    name: "Projector Menu"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xC1AA
          command: 0x59A6
  - platform: template
    name: "Projector Up"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xC1AA
          command: 0x0DF2
  - platform: template
    name: "Projector Down"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xC1AA
          command: 0x4DB2
  - platform: template
    name: "Projector Left"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xC1AA
          command: 0xCD32
  - platform: template
    name: "Projector Right"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xC1AA
          command: 0x8D72
  - platform: template
    name: "Projector Input"
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xC1AA
          command: 0x39C6

  
  